[package]
name = "evercraft"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }

[dev-dependencies]
cucumber = "0.21.0"
futures = "0.3.31"

[[test]]
name = "runner"
harness = false

